config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#index'
  
  get 'users/dexcom_token', to: 'users#dexcom_token'
  get 'welcome/index'

  resources :users, only: [:edit, :update, :show] do
    resources :bolus_doses, only: [:new, :create]
    resources :basal_doses, only: [:new, :create]
  end

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # COMMENTED OUT THE SINATRA GEM - Incase the native ui for sidekiq does not work.
  #require 'sidekiq/web'
  #mount Sidekiq::Web => '/sidekiq
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :basal_doses
    has_many :bolus_doses
    has_many :glucose_readings
    has_one :dexcom_access_token
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  #GET /resource/sign_up
    def new
      super
    end

  #POST /resource
    def create
      super
    end

  #GET /resource/edit
    def edit
      super
    end

  #PUT /resource
    def update
      super
    end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
         @user = current_user
    end

    def edit
        @user = current_user
    end

    def update
        @user = current_user
        @user.update!(user_params)
        
        redirect_to @user
    end 

    def dexcom_token
        current_user.update!(dexcom_authorization_code: params[:code])

        if current_user.save!
            redirect_to current_user
            dexcom_token = Dexcom::Authorization.new(@user.create_token!)
            flash['success'] = 'Congrats! Your Dexcom account is connected'
        else
            redirect_to current_user
            flash['alert'] = 'Try again, please. :) Your Dexcom account did not connect'
        end
    end

    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :basal_insulin, :bolus_insulin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="content">
<div class="row">
<div class="col-sm-6">
<h1>Edit Account Details</h1>
<strong>Here you will enter your basic information that the app needs for baseline tracking.</strong>
<hr>
<p>The app is designed to be user friendly with minimal interaction. It analyzes your blood sugar trends over time and looks for patterns.
<br>
These can be the default patterns or ones set by you. Once the app sees a pattern it starts to look at your sleep and health data.
<br>
These are then the insights that are provided to you. If you have good or bad blood sugars, what other than the obvious could be helping you?
</p>

 <%= form_with(model: @user, local: true) do |form| %>
  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %><br>
    <%= form.label :last_name %><br>
    <%= form.text_field :last_name %>
  </p>
 
  <p>
    <%= form.label :basal_insulin %><br>
    <%= form.text_area :basal_insulin %><br>
    <%= form.label :bolus_insulin %><br>
    <%= form.text_area :bolus_insulin %> 
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>
 <br>
<%= link_to 'Add a Bolus Dose', new_user_bolus_dose_path(@user) %>
<br>
<%= link_to 'Add a Basal Dose', new_user_basal_dose_path(@user) %>
<br>
  <% if @user.dexcom_authorization_code.present? %>
    Dexcom Connected!
  <% else %>
    <%= link_to 'Link Dexcom Account', "#{ENV['DEXCOM_URL']}/v2/oauth2/login?client_id=#{ENV['DEXCOM_ID']}&redirect_uri=#{ENV['DEXCOM_REDIRECT']}&response_type=code&scope=offline_access" %>
  <% end %>

<br>
<%= link_to 'Link FitBit Account', new_user_basal_dose_path(@user) %>
<br>
<%= link_to 'Back', user_path %>
</div>
</div>
</div>

app/views/users/index.html.erb
<div class="content">

<h1>New User?</h1>
<strong>Click the link below to start your path to better insights.</strong><br>
<%= link_to 'New User', new_user_path %><br>
<%= link_to 'Back to the Welcome Page', welcome_index_path %>
&nbsp;
<table>
  <tr>
    <th>Name</th>
    <th>Delivery Methods</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.basal_insulin %></td>
      <td><%= user.bolus_insulin %></td>
    </tr>
  <% end %>
</table>


<h3>Here are your highlights of the week<h4>

</div>

app/views/users/show.html.erb
<div class="content">

<p>
    <strong>Name:</strong>
    <%= @user.first_name %>
    <%= @user.last_name %>
</p>

<p>
    <strong>Liquid Gold:</strong>
    <%= @user.basal_insulin%>
    <%= @user.bolus_insulin%>
</p>
<div class="divider"></div>
<div class="row">
<div class="col s4">
<p>
    <strong>Recent Bolus</strong> <br>
    <% @user.bolus_doses.order(id: :desc).limit(6).each do |dose| %>
      <%= dose.amount %>u - 
      <%= dose.time_stamp.strftime("%l:%M%p").strip %><br>
    <% end %>
</p>
</div>
<div class="col s4">
<p>
    <strong>Basal Records</strong> <br>
    <% @user.basal_doses.order(id: :desc).limit(4).each do |dose| %>
      <%= dose.amount %>u - 
      <%= dose.time_stamp.strftime("%l:%M%p").strip %><br>
    <% end %>
</p>
</div>
<div class="col s4">
<p>
    <strong>Recent BGs</strong> <br>
     <% @user.glucose_readings.each do | reading | %>
      <%= reading.bg_value %>
      <%= reading.time_stamp.strftime("%l:%M%p").strip %>
    <% end %>
</p>
</div>
</div>
<div class="row">
<div class="col s4">
<%= link_to 'Add a Bolus Dose', new_user_bolus_dose_path(@user) %>
</div>
<div class="col s4">
<%= link_to 'Add a Basal Dose', new_user_basal_dose_path(@user) %>
</div>
<div class="col s4">
<%= link_to 'Back', welcome_index_path %>
</div>
</div>
<br>

</div>